### PR TITLE
Add Fathom

### PR DESCRIPTION
**Pull request by mwoodbri**
This enables anonymous page view statistics.

On the downside, cloning and augmenting the [default layout](https://github.com/pages-themes/cayman) with a new `<script>` element means that we've effectively forked the original theme (though it hasn't been updated for a year). And the change would have to re-implemented it we wanted to switch theme.

However, cloning the layout does enable more flexibility with customisation e.g. the footer mis-attributes ownership, and the header could say "Contribute via GitHub" or something.

Further discussion/suggestions very welcome!

### CODE REVIEW

**Comment by cc-a** [comment]
Rather than changing the theme perhaps the best way to do this would be to add the relevant snippet to `_includes/fathom.html`. Then add `{% include fathom.html %}` to the relevant markdown files.

**Comment by mwoodbri** [comment]
I think you may be able to add an intermediate template that does that for you. So it inherits from default and just adds the relevant script block, and then all other pages inherit from it.

However, that wouldn't enable the other changes I alluded to above.

**Comment by cc-a** [comment]
Lets use the intermediate template for now. I'd rather retain flexibility w.r.t the theme for the immediate future.

**Comment by mwoodbri** [comment]
> Lets use the intermediate template for now. I'd rather retain flexibility w.r.t the theme for the immediate future.

Done

**Review by cc-a — APPROVED** [review]
Great. Thank you.

**Pull request merged**
